# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    export TF_CLI_CONFIG_FILE="$HOME/.terraformrc" 
      # echo "credentials \"$(TF_ORG_NAME)/$(TF_WORKSPACE_NAME)\" { token = \"$(TF_API_TOKEN)\" }" > "$TF_CLI_CONFIG_FILE"
       echo "credentials \"app.terraform.io\" { token = \"$(TF_API_TOKEN)\" }" > "$TF_CLI_CONFIG_FILE"
       cd Dev 

       # Initialize Terraform 
       terraform init 
        
       # Plan and Apply 
       terraform plan -out=tfplan